name: trivy

on:
  registry_package:
    types: [ published , updated]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: GHA Trivy
  # You may pin to the exact commit or the version.
  # uses: dataswift/gha-trivy@3ce3259ca6c568d562f73129a3e448558f758196
        uses: dataswift/gha-trivy@v3.0.2
        with:
          # Trivy version
         # trivy_version: # optional, default is latest
          # The target image name of vulnerability scan (specify this parameter or "IMAGE_NAME" environment variable
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # severities of vulnerabilities (separated by commma)
         # severity: # optional, default is HIGH,CRITICAL
          # target vlunerability [os,library] (separated by commma)
        #  vuln_type: # optional, default is os,library
          # Ignore unfixed vulnerabilities [true, false]
       #   ignore_unfixed: # optional, default is false
          # Decide whether to create a issue when vulnerabilities are found [true, false]
        #  issue: # optional, default is true
          # GitHub access token used to create a issue
       #   token: # optional
          # Issue title
      #    issue_title: # optional, default is Security Alert
          # Issue label (separated by commma)
       #   issue_label: # optional, default is trivy,vulnerability
          # Issue assignee (separated by commma)
       #   issue_assignee: # optional
          # Whether the action should fail if a vulnerability was found
       #   fail_on_vulnerabilities: # optional, default is false
   
